### ISSUE TITLE
Error in audiosearch.rb uri saniry check

### ISSUE THREAD

**Issue by RWPCM** [popuparchive/audiosearch-client-ruby#2]
In the following code in `audiosearch.rb`, starting line 67:  
`# sanity check`
      `begin`
        `uri = URI.parse(@host)`
      `rescue URI::InvalidURIError => err`
        `raise "Bad :host value " + err`
      `end`
      `if (!uri.host || !uri.port)`
        `raise "Bad :host value " + @server`
      `end`
``
      `@agent = get_agent()
``
    `end`    
the `@server` variable is not defined when the error is raised, if I am not mistaken ?

**Comment by baileyspace** [comment]
Thanks for catching that :)
